spring:
  application:
    name: sword
  banner:
    location: classpath:banner.txt
    charset: UTF-8
  main:
    banner-mode: console
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
    encoding: UTF-8
  profiles:
    #active: @active.target.profile@
    active: dev

#对外暴露哪些指标
management:
  endpoints:
    web:
      exposure:
        include: '*'
  #激活 promethues 并转换为对应的 promethues 数据
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  #允许对应的数据指标被导出
  metrics:
    export:
      prometheus:
        enabled: true

tianxing:
    key: 629005819119c6f1f0221497e28cf9ed
    base-url: https://apis.tianapi.com
    rainbow-fart: /caihongpi/index




